### ISSUE TITLE
Blank output for Direct Factors and Indirect Factors after tfi.scan

### ISSUE THREAD

**Issue by Harshit-Pateria** [morris-lab/CellOracle#99] opened 2023-01-27 16:29 UTC
I have run the code as intended, I believe there is some incompatibility between the motif datasets and Xenopus laevis 10.1 dataset
Can you look into it?

![image](https://user-images.githubusercontent.com/90829913/215138198-7c4011e3-1b83-47b4-8849-605e617d6571.png)

PS:
Also attaching the processed peak file to help you better understand the issue
[processed_peak_file (1).csv](https://github.com/morris-lab/CellOracle/files/10520912/processed_peak_file.1.csv)

**Comment by KenjiKamimoto-wustl122** [comment] 2023-01-27 17:14
@Harshit-Pateria 

Thank you for reporting issue!
I did motif scan with your peak data, and I got factors like this.
So I don't think the issue you have is due to motif incompatibility. I'm guessing there must be other cause of the issue.
<img width="802" alt="スクリーンショット 2023-01-27 午前11 08 22" src="https://user-images.githubusercontent.com/42547768/215149963-5bd75f95-cccc-4492-9439-ef1fbb07c7a3.png">

I'm suspecting the issue is caused by some updates in the dependent packages used by celloracle. I'd like to know the package versions of them in your environment.
Can you please run the following codes and let me know the results?
```
import celloracle as co
co.check_python_requirements()
```
With this function, you will get table like this.
<img width="495" alt="スクリーンショット 2023-01-27 午前11 11 30" src="https://user-images.githubusercontent.com/42547768/215150719-9732d84e-d8f0-4178-ab74-e69d1e90ff39.png">

**Comment by Harshit-Pateria** [comment] 2023-01-27 17:45
Here is the result
![image](https://user-images.githubusercontent.com/90829913/215157446-13b74384-5609-43f3-bb05-8b6dd94b3efd.png)

**Comment by KenjiKamimoto-wustl122** [comment] 2023-02-02 21:45
@Harshit-Pateria 

I looked into the issue, and I identified the cause of the issue.
There was a bug in a function used to load Xenopys motif data.
I fixed the bug, and released celloracle 0.10.15.

Can you please update celloracle and try motif scan again?
I also updated docker image.

Thank you for your feedback!

**Comment by KenjiKamimoto-wustl122** [comment] 2023-02-07 17:14
@Harshit-Pateria 
I think the issue is solved, and I close the issue.
Please let me know if you still have this issue.

**Closed by KenjiKamimoto-wustl122** 2023-02-07 17:14 UTC
