### ISSUE TITLE
Reducing gene number to 3000 lead to empty overlapping with GRN?

### ISSUE THREAD

**Issue by lingxincheng08** [morris-lab/CellOracle#96] opened 2023-01-19 02:17 UTC
Hi, I am currently trying to process the data. Here is the oracle object of the data. As we can see, the gene number is too much.
![Screenshot 2023-01-18 200707](https://user-images.githubusercontent.com/103924215/213339386-31df991e-dda6-42dd-8923-9849d33262b1.png)
However, if I modify the adata file, by reducing the gene number to 3000 while at the same time including those genes that are in the overlap of GRN and scRNA-seq data, I still get a reported bug by: Found No overlap between TF info (base GRN) and your scRNA-seq data. Please check your data format and species. May I know the possible solution for this situation? (I am using the provided mice GRN and my scRNA seq is also mice data)
Thanks so much!!!!!

**Comment by KenjiKamimoto-wustl122** [comment] 2023-01-21 17:49
@lingxincheng08 
The error message means no TF is included in your scRNA-seq data in your 3000 gene data gene expression matrix.
CellOracle uses transcriptional GRN, and TFs need to be in the scRNA-seq data. 
If not, CellOracle cannot do GRN construction and downstream analysis.

I think the issue is basically same as #97, so let me close this issue.

**Closed by KenjiKamimoto-wustl122** 2023-01-21 17:49 UTC
